#!/usr/bin/env bash
# Configures nginx to add a custom X-Served-By header set to the server's hostname
apt-get -y update
apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sed -i "/listen 80 default_server/a\\\tadd_header X-Served-By \$hostname;" /etc/nginx/sites-available/default
service nginx restart
