#!/usr/bin/env bash
# Installs nginx, configures the redirect, and a custom 404 page
apt-get -y update
apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/listen 80 default_server/a\\tlocation /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }\n\terror_page 404 /404.html;' /etc/nginx/sites-available/default
service nginx restart
